# Generated by Django 4.1.1 on 2022-10-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
