# Generated by Django 4.1.1 on 2022-10-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_rooms_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='bio',
            field=models.CharField(default='Your Bio is Empty...', max_length=1000, null=True),
        ),
    ]
