# Generated by Django 4.1.1 on 2022-10-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rooms_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='bio',
        ),
    ]
